name: dan_app

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.0
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5

dev_dependencies:
  lint: ^1.5.3

flutter:
  uses-material-design: true
