name: dan_app

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.0
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  cloud_firestore: ^2.0.0
  freezed_annotation: ^0.14.1
  dan_tasks:
    path: ../dan_tasks

dev_dependencies:
  lint: ^1.5.3
  dart_code_metrics: ^3.2.0-dev.1
  build_runner: ^1.12.0
  freezed: ^0.14.1

flutter:
  uses-material-design: true
