name: dan_tasks

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.0.0
  flutter_hooks: ^0.16.0
  linked_scroll_controller: ^0.2.0-nullsafety.0


dev_dependencies:
  lint: ^1.5.3
  dart_code_metrics: ^3.1.0

