name: dan_tasks

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lint: ^1.5.3
  dart_code_metrics: ^3.1.0

flutter:
